import './globals.css'
import Header from './components/Header'
import HeroBody from './components/HeroBody'
import TraderStat from './components/TraderStat'
import GetStarted from './components/GetStarted'
import FundsProperties from './components/FundsProperties'
import EosiSection7 from './components/EosiSection7'
import FinanceNumbers from './components/FinanceNumbers'
import EosiSection8 from './components/EosiSection8'
import Testimonial from './components/Testimonial'
import EosiSection9 from './components/EosiSection9'
import BannerSection10 from './components/BannerSection10'
import EosiTeamsection11 from './components/EosiTeamsection11'



export const metadata = {
  title: 'EOSI Finance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        <HeroBody />
        <TraderStat />
        <GetStarted />
        <FundsProperties />
        <EosiSection7 />
        <FinanceNumbers />
        <EosiSection8 />
        <Testimonial />
        <EosiSection9 />
        <BannerSection10 />
        <EosiTeamsection11 />
        {/* <Slider /> */}
        {/* <Rotate /> */}
        {children}

      </body>
    </html>
  )
}
